---

- name: Ensure gunicorn is installed
  pip: virtualenv={{ virtualenv_path }} name=gunicorn

- name: Create the Gunicorn conf file
  template: src=gunicorn.conf.j2
            dest={{ project_path }}/gunicorn.conf.py
            owner=ubuntu
            group=ubuntu
            mode=0755

- name: Create the Supervisor conf file
  template: src=supervisor.conf.j2
            dest=/etc/supervisor/conf.d/{{ project_name }}.conf

- name: Restart Supervisor
  supervisorctl: name={{ project_name }} state=restarted

- name: Restart Supervisor Service
  service: name=supervisor state=restarted