---

- name: setup_git_repo
  git: repo={{ git_repo }} dest={{ project_path }} accept_hostkey=yes
  tags: git

- name: Ensure user owns our project
  file: state=directory path={{ project_path }} owner=ubuntu